apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: externaldns
spec:
  ports:
  - name: http
    port: 2379
  - name: peer
    port: 2380
  selector:
    k8s-app: etcd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: externaldns
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: etcd
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: etcd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ''
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      containers:   
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.5
        command: ["/usr/local/bin/etcd"]
        args:
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://0.0.0.0:2379
        - --data-dir=/var/lib/etcd
        livenessProbe:
          failureThreshold: 5
          tcpSocket:
            port: 2379
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: etcd-http 
          containerPort: 2379
          protocol: TCP
        - name: etcd-peer
          containerPort: 2380
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi