apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: cert@xiaomo.io
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: istio

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cert@xiaomo.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: istio

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-xiaomo-io
  namespace: istio-system
spec:
  secretName: istio-xiaomo-io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: istio.xiaomo.io
  dnsNames:
  - istio.xiaomo.io
